// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/amrnt/ent-oso/ent/runtime.go

const (
	Version = "v0.10.2-0.20220705102915-5b67bdab4fe4"           // Version of ent codegen.
	Sum     = "h1:JyroITZD3l091n0jtrJqag+cH5Sw5vzKokUDhWsrcpA=" // Sum of ent codegen.
)
